# Example configuration for denote-tasks
# Copy this to ~/.config/denote-tasks/config.toml and modify as needed

# Required: Path to your Denote notes directory
notes_directory = "~/notes"

# Optional: External editor (defaults to vim)
editor = "vim"

# Optional: Default area for new tasks
default_area = ""

# Optional: Days horizon for "soon" filter (defaults to 3)
soon_horizon = 3

# Optional: TUI theme settings
[tui]
theme = "default"  # Options: default, dark, light, high-contrast, minimal

# Optional: Notes mode default sort settings
[notes]
sort_by = "modified"    # Options: modified, created, title
sort_order = "reverse"  # Options: normal, reverse (reverse = newest first)

# Optional: Tasks mode default sort settings
[tasks]
sort_by = "due"        # Options: due, priority, estimate, title, created
sort_order = "normal"  # Options: normal, reverse (normal = closest due dates first)