# Example configuration for denote-tasks
# Copy this to ~/.config/denote-tasks/config.toml and modify as needed

# Required: Path to your task directory
# This is where your task and project files live
notes_directory = "~/tasks"

# Optional: External editor (defaults to vim)
editor = "vim"

# Optional: Default area for new tasks
default_area = ""

# Optional: Days horizon for "soon" filter (defaults to 3)
soon_horizon = 3

# Optional: TUI theme settings
[tui]
theme = "default"  # Options: default, dark, light, high-contrast, minimal

# Optional: Task sorting preferences
[tasks]
sort_by = "due"        # Options: due, priority, project, estimate, title, created, modified
sort_order = "normal"  # Options: normal, reverse (normal = closest due dates first)